---
kind: pipeline
type: docker
name: code-build-deploy
steps:
  - name: build-deploy
    image: appleboy/drone-ssh
    pull: if-not-exists
    settings:
      host:
        from_secret: host
      username:
        from_secret: username
      password:
        from_secret: password
      port: 22
      command_timeout: 10m
      script_stop: false # 设置为false，遇到第一次错误会继续运行后面的命令
      script:
        - cd /home/${DRONE_REPO_OWNER}/apps/${DRONE_REPO_NAME}
        - git switch main
        - git pull
        - docker-compose  -f docker-compose.prod.yml down # 先停下
        - docker-compose  -f docker-compose.prod.yml build # 构建镜像
        - docker-compose  -f docker-compose.prod.yml up -d  # 重新启动
    when:
      event: [ push, pull_request ]
      branch: [ master ]

  - name: push-to-gitee
    image: appleboy/drone-git-push
    pull: if-not-exists
    settings:
      branch: master
      remote: git@gitee.com:nhnhwsnh/fastapi_demo.git
      force: false
      commit: true
      ssh_key:
        from_secret: gitee_ssh_key
    when:
      event: [ push, pull_request ]
      branch: [ development ]